# Generated by Django 5.1.5 on 2025-01-30 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
