# Generated by Django 5.1.5 on 2025-01-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='data',
            field=models.JSONField(db_index=True),
        ),
    ]
